development:
  adapter: postgresql
  database: fulbo_development
  host: localhost
  username: rails
  password: root
  pool: 5

test:
  adapter: postgresql
  database: fulbo_test
  host: localhost
  username: rails
  password: root
  pool: 5

#  not sure if this go
production:
  adapter: postgresql
  database: fulbo_production
  host: localhost
  username: rails
  password: root
  pool: 5
